# Generated by Django 2.0.1 on 2018-02-25 03:04

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('basepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clubeleven_models.BasePost')),
                ('href', models.URLField(max_length=2048)),
                ('hreflang', models.CharField(max_length=8, null=True)),
                ('height', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('preview', models.TextField()),
            ],
            bases=('clubeleven_models.basepost',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clubeleven_models.BasePost')),
                ('content', models.TextField()),
                ('source', models.TextField()),
            ],
            bases=('clubeleven_models.basepost',),
        ),
        migrations.AddField(
            model_name='basepost',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='basepost',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='basepost',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='basepost',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubeleven_models.BaseActor'),
        ),
        migrations.AddField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='basepost',
            name='name',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clubeleven_models.Post')),
            ],
            bases=('clubeleven_models.post',),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clubeleven_models.Comment')),
                ('type', models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike'), ('SEEN', 'Seen')], max_length=8)),
            ],
            bases=('clubeleven_models.comment',),
        ),
        migrations.AddField(
            model_name='comment',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clubeleven_models.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='clubeleven_models.Post'),
        ),
    ]
