# Generated by Django 2.0.1 on 2018-03-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0002_auto_20180313_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='shortname',
            field=models.SlugField(default='fixme-2018-03-18 17:28:07.320745+00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basepost',
            name='icon',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='basepost',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
