# Generated by Django 2.0.1 on 2018-02-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0002_auto_20180225_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='emojo',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='reaction',
            name='shortcode',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
