# Generated by Django 2.0.1 on 2018-03-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0003_auto_20180318_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='_persona_followers_+', to='clubeleven_models.Persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='follows',
            field=models.ManyToManyField(null=True, related_name='_persona_follows_+', to='clubeleven_models.Persona'),
        ),
    ]
