# Generated by Django 2.1.4 on 2018-12-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0005_auto_20180320_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseactor',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_baseactor_followers_+', to='clubeleven_models.BaseActor'),
        ),
        migrations.AlterField(
            model_name='baseactor',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='_baseactor_follows_+', to='clubeleven_models.BaseActor'),
        ),
    ]
