# Generated by Django 2.1.4 on 2018-12-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0006_auto_20181214_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseactor',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
