# Generated by Django 2.1.4 on 2018-12-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0007_baseactor_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseactor',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseactor',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
