# Generated by Django 2.1.4 on 2018-12-17 14:43

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0008_auto_20181214_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectableMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, max_length=4096, null=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('host', models.CharField(blank=True, max_length=2048, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('digest', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
