# Generated by Django 2.1.4 on 2018-12-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0010_auto_20181217_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectablemessage',
            name='signature_check_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectablemessage',
            name='signature_checked',
            field=models.BooleanField(default=False),
        ),
    ]
