# Generated by Django 2.1.4 on 2018-12-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0011_auto_20181217_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectablemessage',
            name='date',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
