# Generated by Django 2.1.4 on 2018-12-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0012_auto_20181217_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectablemessage',
            name='request_target',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
