# Generated by Django 2.1.4 on 2018-12-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0013_inspectablemessage_request_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseactor',
            name='icon_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='baseactor',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='baseactor',
            name='type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
