# Generated by Django 2.1.4 on 2018-12-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0014_auto_20181220_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='avatar',
        ),
        migrations.AddField(
            model_name='baseactor',
            name='icon',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='baseactor',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
