# Generated by Django 2.1.4 on 2018-12-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubeleven_models', '0016_auto_20181220_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseactor',
            name='profile_url',
            field=models.URLField(max_length=2048, unique=True),
        ),
    ]
