# Generated by Django 2.0.1 on 2018-01-25 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('media_type', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activitypub.Common')),
                ('href', models.URLField()),
                ('rel', models.CharField(blank=True, max_length=20, null=True)),
                ('hreflang', models.CharField(blank=True, max_length=8, null=True)),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
            ],
            bases=('activitypub.common',),
        ),
    ]
