# Generated by Django 2.0.1 on 2018-01-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='preview',
            field=models.ManyToManyField(related_name='preview_of', to='activitypub.Common'),
        ),
    ]
