# Generated by Django 2.0.1 on 2018-01-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0003_pubobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='at_context',
            field=models.CharField(default='https://w3c.org/ns/activitystreams', max_length=2048),
        ),
        migrations.AddField(
            model_name='common',
            name='object_type',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
