# Generated by Django 2.0.1 on 2018-01-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0003_pubobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('pubobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activitypub.PubObject')),
            ],
            bases=('activitypub.pubobject',),
        ),
        migrations.CreateModel(
            name='OrderedCollection',
            fields=[
                ('collection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activitypub.Collection')),
            ],
            options={
                'ordering': ['-published'],
            },
            bases=('activitypub.collection',),
        ),
        migrations.AddField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(related_name='in_collections', to='activitypub.Common'),
        ),
    ]
