# Generated by Django 2.0.1 on 2018-01-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0004_auto_20180127_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('pubobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activitypub.PubObject')),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followers_owner', to='activitypub.Collection')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='following_owner', to='activitypub.Collection')),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbox_owner', to='activitypub.OrderedCollection')),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liked_owner', to='activitypub.Collection')),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_owner', to='activitypub.OrderedCollection')),
            ],
            bases=('activitypub.pubobject',),
        ),
    ]
