# Generated by Django 2.0.1 on 2018-01-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0005_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseActivity',
            fields=[
                ('pubobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activitypub.PubObject')),
            ],
            bases=('activitypub.pubobject',),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('baseactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activitypub.BaseActivity')),
                ('direct_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_object_of', to='activitypub.PubObject')),
            ],
            bases=('activitypub.baseactivity',),
        ),
        migrations.CreateModel(
            name='IntransitiveActivity',
            fields=[
                ('baseactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activitypub.BaseActivity')),
            ],
            bases=('activitypub.baseactivity',),
        ),
        migrations.AddField(
            model_name='baseactivity',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_of', to='activitypub.PubObject'),
        ),
        migrations.AddField(
            model_name='baseactivity',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_of', to='activitypub.PubObject'),
        ),
        migrations.AddField(
            model_name='baseactivity',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_of', to='activitypub.PubObject'),
        ),
        migrations.AddField(
            model_name='baseactivity',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitypub.Actor'),
        ),
        migrations.AddField(
            model_name='baseactivity',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_of', to='activitypub.PubObject'),
        ),
    ]
